apiVersion: v1
kind: Service
metadata:
  name: qdrant-headless
  namespace: <NAMESPACE>
spec:
  clusterIP: None
  selector:
    app: qdrant
  ports:
    - name: grpc
      port: 6334
      targetPort: 6334
    - name: http
      port: 6333
      targetPort: 6333
    - name: p2p
      port: 6335
      targetPort: 6335
---
apiVersion: v1
kind: Service
metadata:
  name: qdrant
  namespace: <NAMESPACE>
spec:
  type: ClusterIP
  selector:
    app: qdrant
  ports:
    - name: grpc
      port: 6334
      targetPort: 6334
    - name: http
      port: 6333
      targetPort: 6333
