resources:
  - namespace.yaml
  - secret.yaml
  - embed/deployment.yaml
  - embed/service.yaml
  - qdrant/statefulset.yaml
  - qdrant/service.yaml
  - chat-api/deployment.yaml
  - chat-api/service.yaml
  - admin-api/deployment.yaml
  - admin-api/service.yaml
  - ingress.yaml
