resources:
  - namespace.yaml
  - secret.yaml
  - kf-api/deployment.yaml
  - kf-api/service.yaml
  - embed/deployment.yaml
  - embed/service.yaml
  - qdrant/statefulset.yaml
  - qdrant/service.yaml
  - ingress.yaml
