apiVersion: v1
kind: ConfigMap
metadata:
  name: kf-config
  namespace: <NAMESPACE>
data:
  llm.yaml: |
    <LLM_CONFIG>
  embed.yaml: |
    <EMBED_CONFIG>
  session.yaml: |
    <SESSION_CONFIG>
  logging.yaml: |
    <LOGGING_CONFIG>
  db.yaml: |
    <DB_CONFIG>
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: workflow-config
  namespace: <NAMESPACE>
data:
  workflows.yaml: |
    <WORKFLOWS_CONFIG>
  nodes.yaml: |
    <NODES_CONFIG>
