apiVersion: v1
kind: Service
metadata:
  name: kf-qdrant
  namespace: <NAMESPACE>
spec:
  type: ClusterIP
  selector:
    app: kf-qdrant
  ports:
    - name: grpc
      port: 6334
      targetPort: 6334
    - name: http
      port: 6333
      targetPort: 6333
